//go:build !ignore_autogenerated

// Copyright 2026 The Steward Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAIJob) DeepCopyInto(out *PolicyAIJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAIJob.
func (in *PolicyAIJob) DeepCopy() *PolicyAIJob {
	if in == nil {
		return nil
	}
	out := new(PolicyAIJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyAIJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAIJobList) DeepCopyInto(out *PolicyAIJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyAIJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAIJobList.
func (in *PolicyAIJobList) DeepCopy() *PolicyAIJobList {
	if in == nil {
		return nil
	}
	out := new(PolicyAIJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyAIJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAIJobSpec) DeepCopyInto(out *PolicyAIJobSpec) {
	*out = *in
	if in.ReadCategoryIDs != nil {
		in, out := &in.ReadCategoryIDs, &out.ReadCategoryIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Input.DeepCopyInto(&out.Input)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAIJobSpec.
func (in *PolicyAIJobSpec) DeepCopy() *PolicyAIJobSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyAIJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAIJobStatus) DeepCopyInto(out *PolicyAIJobStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAIJobStatus.
func (in *PolicyAIJobStatus) DeepCopy() *PolicyAIJobStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyAIJobStatus)
	in.DeepCopyInto(out)
	return out
}
